# Generated by Django 3.1.1 on 2023-06-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
