# Generated by Django 3.1.1 on 2023-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
